In [6]:
import numpy as np
import sympy
x = sympy.symbols('x')

In [3]:
a1 = np.array([[-5, -6, 4, -2, 64], [0, 3, -4, -6, -55], [2, 4, -4, 2, -48], [1, -8, 2, 8, 68]]).astype(np.float64)
a2 = np.array([[-2, -9, -3, 7, -26], [-7, 2, 2, 5, -25], [-6, 2, 0, 0, -16], [0, -3, 8, -3, -5]]).astype(np.float64)
a3 = np.array([[-2, -1, -9, -5, 93], [-4, 4, -2, 6, 16], [0, 5, 7, -4, -80], [0, 9, 7, 7, -119]]).astype(np.float64)
a4 = np.array([[1, 4, -9, 7, -67], [2, -2, -2, 3, -57], [-1, 3, -9, -1, -26], [-5, 2, 2, 1, 52]]).astype(np.float64)
a5 = np.array([[9, -7, -1, 1, 55], [2, 7, 3, -6, -66], [4, 7, -3, -7, -43], [-9, -5, -1, -6, -24]]).astype(np.float64)
a6 = np.array([[-5, 2, 4, -4, 57], [4, 9, -7, -5, -23], [0, -5, 6, 7, 23], [4, 8, -6, -6, -20]]).astype(np.float64)
a = [a1, a2, a3, a4, a5, a6]

In [23]:
def gauss(x):
    for i in range(len(x)):
        for j in range(i, len(x)):
            if (j == i):
                max_el = abs(x[i][j])
                index = i
                for z in range(j, len(x)):
                    if (max_el < abs(x[z][j])):
                        max_el = abs(x[z][j])
                        index = z
                x[i], x[index] == x[index], x[i]
                x[i] /= x[j][i]
            else:
                x[j] -= x[i] * (x[j][i])
    for i in range(len(x) - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            x[j] -= x[i] * (x[j][i])
    for i in range(len(x)):
        print ("x", i + 1, " = ", x[i][len(x[i]) - 1], sep = "")

In [4]:
gauss(a[0])

x1 = -2.0
x2 = -5.0
x3 = 7.0
x4 = 2.0


In [25]:
gauss(a[1])

[[  1.    4.5   1.5  -3.5  13. ]
 [  0.   33.5  12.5 -19.5  66. ]
 [  0.   29.    9.  -21.   62. ]
 [  0.   -3.    8.   -3.   -5. ]]
[[  1.           4.5          1.5         -3.5         13.        ]
 [  0.           1.           0.37313433  -0.58208955   1.97014925]
 [  0.           0.          -1.82089552  -4.11940299   4.86567164]
 [  0.           0.           9.11940299  -4.74626866   0.91044776]]
[[  1.           4.5          1.5         -3.5         13.        ]
 [  0.           1.           0.37313433  -0.58208955   1.97014925]
 [ -0.          -0.           1.           2.26229508  -2.67213115]
 [  0.           0.           0.         -25.37704918  25.27868852]]
[[  1.           4.5          1.5         -3.5         13.        ]
 [  0.           1.           0.37313433  -0.58208955   1.97014925]
 [ -0.          -0.           1.           2.26229508  -2.67213115]
 [ -0.          -0.          -0.           1.          -0.99612403]]
x1 = 3.18217054264
x2 = 1.54651162791
x3 = -0.41

In [5]:
gauss(a[2])

x1 = -9.0
x2 = -7.0
x3 = -7.0
x4 = -1.0


In [17]:
gauss(a[3])

x1 = -5.0
x2 = 9.0
x3 = 7.0
x4 = -5.0


In [18]:
gauss(a[4])

x1 = 2.0
x2 = -4.0
x3 = -4.0
x4 = 5.0


In [19]:
gauss(a[5])

x1 = -3.0
x2 = 5.0
x3 = 8.0
x4 = -0.0


In [1]:
def gauss(x):
    for i in range(len(x)):
        b = 0
        for j in range(i, len(x)):
            if (b == 1): break
            if (j == i):
                for z in range(i, len(x)):
                    if (x[z][i] != 0):
                        x[z] /= x[z][i]
                        x[z], x[i] = x[i], x[z]
                        break
                    if (z == len(x) - 1):
                        b = 1
            else:
                x[j] -= x[i] * (x[j][i])
    #print(x)
    for i in range(len(x) - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            x[j] -= x[i] * (x[j][i])
    #print(x)
    for i in range(len(x)):
        print ("x", i + 1, " = ", x[i][len(x[i]) - 1], sep = "")