In [2]:
import numpy as np

In [3]:
a1 = np.array([[15, -4, -6, 5, 104], [4, -14, -1, 4, 70], [7, -7, 27, -8, 170], [-3, -3, 2, -14, 48]]).astype(np.float64)
a2 = np.array([[16, 0, -2, 7, 50], [-1, 14, -3, 2, 2], [5, 5, 26, 7, 273], [-2, -6, 9, 24, 111]]).astype(np.float64)
a3 = np.array([[-2, -7, -8, -2, -51], [2, -17, -6, -2, 85], [-7, -6, -23, -3, 71], [3, -2, -7, -13, 91]]).astype(np.float64)
a4 = np.array([[10, 0, 2, 4, 110], [2, 16, -3, 8, 128], [1, 5, 11, -4, 102], [8, 1, 6, -17, 81]]).astype(np.float64)
a5 = np.array([[15, 3, -5, -5, 36], [7, -15, -6, 1, -112], [-4, 7, -19, -6, 19], [3, 0, -5, 8, -23]]).astype(np.float64)
a6 = np.array([[22, -3, -8, 7, -158], [-8, -22, -4, -8, 254], [8, -2, -18, 2, -108], [7, 2, -9, -24, -24]]).astype(np.float64)
exam = np.array([[12, -3, -1, 3, -31], [5, 20, 9, 1, 90], [6, -3, -21, -7, 119], [8, -7, 3, -27, 71]]).astype(np.float64)
SLAU = [a1, a2, a4, a5, a6]
eps = 0.001

In [4]:
a1 = np.array([[15, -1, 2, 1], [1, -23, 1, -1], [1, 3, 30, 2]]).astype(np.float64)
eps = 0.0001

In [5]:
def it_method(x, eps):
    a = -x[:, :len(x[0]) - 1]
    b = x[:, -1]
    for i in range(len(x)):
        b[i] /= -a[i][i]
        a[i] /= -a[i][i]
        a[i][i] = 0
    boof = 0
    new_x = b
    it = 0
    while(42):
        it += 1
        z = np.zeros(len(x))
        for i in range(len(x)):
            for j in range(len(new_x)):
                z[i] += a[i][j] * new_x[j]
            z[i] += b[i]
        d = 0
        for i in range(len(z)):
            if (abs(z[i] - new_x[i]) < eps):
                d += 1
        boof = new_x
        new_x = z
        if (d == len(z)): break
    print(it)
    print(new_x)

In [6]:
for i in range(len(SLAU)):
    it_method(SLAU[i], eps)

15
[ 8.00000911 -4.0000013   1.99998884 -3.99999261]
13
[ 3.33945063  1.99864502  8.91932508  2.05817922]
18
[ 9.00000926  7.00000248  6.00004307  1.99996668]
50
[ 1.0000526   6.99999506  1.99994683 -1.99998087]
14
[-5.99999811 -9.00000181  4.00000556 -2.99997302]


In [19]:
it_method(a1, eps)

3
[ 0.06195307  0.04876763  0.05972911]


In [5]:
a1 = np.array([[15, -4, -6, 5, 104], [4, -14, -1, 4, 70], [7, -7, 27, -8, 170], [-3, -3, 2, -14, 48]]).astype(np.float64)
a2 = np.array([[16, 0, -2, 7, 50], [-1, 14, -3, 2, 2], [5, 5, 26, 7, 273], [-2, -6, 9, 24, 111]]).astype(np.float64)
a3 = np.array([[-2, -7, -8, -2, -51], [2, -17, -6, -2, 85], [-7, -6, -23, -3, 71], [3, -2, -7, -13, 91]]).astype(np.float64)
a4 = np.array([[10, 0, 2, 4, 110], [2, 16, -3, 8, 128], [1, 5, 11, -4, 102], [8, 1, 6, -17, 81]]).astype(np.float64)
a5 = np.array([[15, 3, -5, -5, 36], [7, -15, -6, 1, -112], [-4, 7, -19, -6, 19], [3, 0, -5, 8, -23]]).astype(np.float64)
a6 = np.array([[22, -3, -8, 7, -158], [-8, -22, -4, -8, 254], [8, -2, -18, 2, -108], [7, 2, -9, -24, -24]]).astype(np.float64)
SLAU = [a1, a2, a3, a4, a5, a6]

In [20]:
a1 = np.array([[15, -1, 2, 1], [1, -23, 1, -1], [1, 3, 30, 2]]).astype(np.float64)
eps = 0.0001

In [21]:
def Seidel_method(x, eps):
    a = x[:, :len(x[0]) - 1]
    b = x[:, -1]
    a = a.T
    c = a.dot(a.T)
    d = np.zeros(len(b))
    for i in range(len(b)):
        for j in range(len(a[i])):
            d[i] += b[j] * a[i][j]
    a = a.T
    for i in range(len(c)):
        d[i] /= c[i][i]
        c[i] /= c[i][i]
        c[i][i] = 0  
    boof = 0
    new_x = b
    it = 0
    while(42):
        it += 1
        z = np.zeros(len(x))
        for i in range(len(x)):
            for j in range(len(new_x)):
                z[i] -= c[i][j] * new_x[j]
            z[i] += d[i]
        f = 0
        for i in range(len(z)):
            if (abs(z[i] - new_x[i]) < eps):
                f += 1
        boof = new_x
        new_x = z
        if (f == len(z)): break
    print(new_x, it)

In [7]:
for i in range(len(SLAU)):
    Seidel_method(SLAU[i], eps)

[ 8.00027505 -4.00039888  2.0002445  -4.00022779] 56
[ 3.339216    1.99868247  8.91908454  2.05793797] 31


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: RuntimeWarning: overflow encountered in double_scalars
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: RuntimeWarning: overflow encountered in double_scalars
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in double_scalars


KeyboardInterrupt: 

In [22]:
Seidel_method(a1, eps)

[ 0.06194643  0.04876385  0.05972894] 8


In [34]:
a1 = np.array([[15, -4, -6, 5, 104], [4, -14, -1, 4, 70], [7, -7, 27, -8, 170], [-3, -3, 2, -14, 48]]).astype(np.float64)
a2 = np.array([[16, 0, -2, 7, 50], [-1, 14, -3, 2, 2], [5, 5, 26, 7, 273], [-2, -6, 9, 24, 111]]).astype(np.float64)
a3 = np.array([[-2, -7, -8, -2, -51], [2, -17, -6, -2, 85], [-7, -6, -23, -3, 71], [3, -2, -7, -13, 91]]).astype(np.float64)
a4 = np.array([[10, 0, 2, 4, 110], [2, 16, -3, 8, 128], [1, 5, 11, -4, 102], [8, 1, 6, -17, 81]]).astype(np.float64)
a5 = np.array([[15, 3, -5, -5, 36], [7, -15, -6, 1, -112], [-4, 7, -19, -6, 19], [3, 0, -5, 8, -23]]).astype(np.float64)
a6 = np.array([[22, -3, -8, 7, -158], [-8, -22, -4, -8, 254], [8, -2, -18, 2, -108], [7, 2, -9, -24, -24]]).astype(np.float64)
SLAU = [a1, a2, a4, a5, a6]

In [13]:
def Seidel_method(x, eps):
    a = x[:, :len(x[0]) - 1]
    b = x[:, -1]
    a = a.T
    c = a.dot(a.T)
    d = np.zeros(len(b))
    for i in range(len(b)):
        for j in range(len(a[i])):
            d[i] += b[j] * a[i][j]
    a = a.T
    for i in range(len(c)):
        d[i] /= c[i][i]
        c[i] /= c[i][i]
        c[i][i] = 0  
    boof = 0
    new_x = b
    it = 0
    while(42):
        it += 1
        print(it, new_x)
        z = np.zeros(len(x))
        for i in range(len(x)):
            for j in range(len(new_x)):
                z[i] -= c[i][j] * new_x[j]
            z[i] += d[i]
        f = 0
        for i in range(len(z)):
            if (abs(z[i] - new_x[i]) < eps * 10):
                print(it)
                print(z[i] - new_x[i])
            if (abs(z[i] - new_x[i]) < eps):
                f += 1
        print()
        boof = new_x
        new_x = z
        if (f == len(z)): break
    print(new_x, it)

In [14]:
Seidel_method(exam, eps)

1 [ -31.   90.  119.   71.]

2 [ 96.20074349 -89.37259101 -54.40977444 -48.14467005]

3 [-51.0609433   53.28303804  54.07537692  53.03478136]

4 [ 63.68988454 -50.01981996 -39.05149042 -37.43934421]

5 [-37.0226347   40.12115474  31.76634268  31.64186861]

6 [ 40.22072372 -28.84690881 -28.76886494 -27.84373553]

7 [-25.85729137  30.1234848   18.4690477   18.30129717]

8 [ 25.6765079  -15.88799855 -21.28689959 -20.75011904]

9 [-17.73402189  22.85030791  10.1418934    9.97805414]

10 [ 16.55587908  -7.76320385 -16.03080205 -15.71245828]

11 [-12.01992872  17.73863497   4.84092767   4.70750198]

12 [ 10.75441743  -2.59264657 -12.4144889  -12.22095134]

13 [ -8.08354141  14.21977392   1.42915184   1.32934857]

14 [ 7.02333776  0.73408862 -9.95850862 -9.83832164]

15 [ -5.40785132  11.82905118  -0.78421142  -0.85552877]

16 [ 4.60420141  2.89173644 -8.304662   -8.22875739]

17 [ -3.60499876  10.2187288   -2.22834637  -2.27795226]

18 [ 3.02645259  4.29926209 -7.19726754 -7.14870921]

19 [-